import type { IconType } from "react-icons";
import {
  FaAward,
  FaBeer,
  FaBell,
  FaBirthdayCake,
  FaBook,
  FaBrain,
  FaBriefcase,
  FaBullhorn,
  FaBus,
  FaCalendar,
  FaCalendarAlt,
  FaCalendarCheck,
  FaCamera,
  FaChalkboardTeacher,
  FaChess,
  FaClock,
  FaCode,
  FaCoffee,
  FaFilm,
  FaFlag,
  FaFlask,
  FaFutbol,
  FaGamepad,
  FaGift,
  FaGithub,
  FaGlobe,
  FaGraduationCap,
  FaGuitar,
  FaHamburger,
  FaHandshake,
  FaHeart,
  FaHiking,
  FaLaptopCode,
  FaLightbulb,
  FaLinux,
  FaMapMarkerAlt,
  FaMedal,
  FaMicrophone,
  FaMoneyBillWave,
  FaMusic,
  FaPalette,
  FaPizzaSlice,
  FaRobot,
  FaRocket,
  FaRunning,
  FaSchool,
  FaStar,
  FaTerminal,
  FaTicketAlt,
  FaTools,
  FaTrophy,
  FaTshirt,
  FaUserGraduate,
  FaUsers,
  FaUsersCog,
  FaUtensils,
} from "react-icons/fa";
import {
  MdCameraAlt,
  MdCampaign,
  MdCardGiftcard,
  MdCelebration,
  MdCode,
  MdComputer,
  MdDirectionsBus,
  MdEmojiEvents,
  MdEvent,
  MdEventAvailable,
  MdFavorite,
  MdGroups,
  MdLightbulb,
  MdLocalBar,
  MdLocalCafe,
  MdLocalPizza,
  MdMenuBook,
  MdMic,
  MdMovie,
  MdMusicNote,
  MdPalette,
  MdRestaurant,
  MdSchool,
  MdScience,
  MdSportsEsports,
  MdSportsSoccer,
  MdStar,
  MdVolunteerActivism,
  MdWork,
} from "react-icons/md";
import {
  IoBasketball,
  IoBeer,
  IoBook,
  IoBriefcase,
  IoBulb,
  IoBus,
  IoCafe,
  IoCalendar,
  IoCalendarNumber,
  IoCamera,
  IoCart,
  IoCodeSlash,
  IoColorPalette,
  IoFilm,
  IoFlask,
  IoFootball,
  IoGameController,
  IoGift,
  IoGlobe,
  IoHeart,
  IoLibrary,
  IoMegaphone,
  IoMicOutline,
  IoMusicalNotes,
  IoPeople,
  IoPizza,
  IoRestaurant,
  IoRocket,
  IoSchool,
  IoShirt,
  IoStar,
  IoTicket,
  IoTrophy,
  IoWine,
} from "react-icons/io5";
import {
  TbAward,
  TbBallFootball,
  TbBeer,
  TbBook,
  TbBrain,
  TbBriefcase,
  TbBulb,
  TbBus,
  TbCake,
  TbCalendarEvent,
  TbCalendarTime,
  TbCamera,
  TbChess,
  TbCode,
  TbCoffee,
  TbConfetti,
  TbDeviceGamepad,
  TbDeviceLaptop,
  TbFlask,
  TbGift,
  TbHeart,
  TbMedal,
  TbMicrophone,
  TbMovie,
  TbMusic,
  TbPalette,
  TbPizza,
  TbPresentation,
  TbRobot,
  TbRocket,
  TbSchool,
  TbShirt,
  TbSpeakerphone,
  TbStar,
  TbTerminal2,
  TbTicket,
  TbToolsKitchen2,
  TbTrophy,
  TbUsers,
  TbWorld,
} from "react-icons/tb";
import {
  GiBeerStein,
  GiBookshelf,
  GiBrain,
  GiCakeSlice,
  GiCampfire,
  GiChessKnight,
  GiCoffeeCup,
  GiFilmProjector,
  GiFullPizza,
  GiGraduateCap,
  GiGuitar,
  GiHeartPlus,
  GiLaptop,
  GiMicrophone,
  GiPaintBrush,
  GiPartyPopper,
  GiPodium,
  GiPresent,
  GiProcessor,
  GiRobotGolem,
  GiRocketFlight,
  GiRunningShoe,
  GiSoccerBall,
  GiTicket,
  GiTrophy,
  GiVideoCamera,
} from "react-icons/gi";
import {
  HiAcademicCap,
  HiBeaker,
  HiBookOpen,
  HiCake,
  HiCalendarDays,
  HiCamera,
  HiCodeBracket,
  HiComputerDesktop,
  HiFilm,
  HiGift,
  HiGlobeAlt,
  HiHeart,
  HiLightBulb,
  HiMegaphone,
  HiMicrophone,
  HiMusicalNote,
  HiPaintBrush,
  HiRocketLaunch,
  HiSparkles,
  HiStar,
  HiTicket,
  HiTrophy,
  HiUserGroup,
} from "react-icons/hi2";
import {
  BsBalloon,
  BsBank,
  BsBook,
  BsBriefcase,
  BsCalendar2Check,
  BsCalendarEvent,
  BsCamera,
  BsCart,
  BsCodeSlash,
  BsController,
  BsCupHot,
  BsEggFried,
  BsFilm,
  BsGift,
  BsGlobe,
  BsHeart,
  BsLaptop,
  BsLightbulb,
  BsMegaphone,
  BsMicFill,
  BsMortarboard,
  BsMusicNoteBeamed,
  BsPalette,
  BsPeople,
  BsRobot,
  BsRocketTakeoff,
  BsStar,
  BsTerminal,
  BsTicketPerforated,
  BsTrophy,
} from "react-icons/bs";

/**
 * Curated catalogue of icons offered by the event icon picker.
 *
 * Historically the picker offered every export of seven `react-icons` packs
 * (~21k components) through namespace imports, which shipped all of them to the
 * `/activities` client bundle. Only the icons listed here are bundled now; icons
 * saved before this catalogue existed are still resolved on demand by
 * `loadLegacyEventIcon`.
 */
export const ICON_REGISTRY: Record<string, IconType> = {
  FaAward,
  FaBeer,
  FaBell,
  FaBirthdayCake,
  FaBook,
  FaBrain,
  FaBriefcase,
  FaBullhorn,
  FaBus,
  FaCalendar,
  FaCalendarAlt,
  FaCalendarCheck,
  FaCamera,
  FaChalkboardTeacher,
  FaChess,
  FaClock,
  FaCode,
  FaCoffee,
  FaFilm,
  FaFlag,
  FaFlask,
  FaFutbol,
  FaGamepad,
  FaGift,
  FaGithub,
  FaGlobe,
  FaGraduationCap,
  FaGuitar,
  FaHamburger,
  FaHandshake,
  FaHeart,
  FaHiking,
  FaLaptopCode,
  FaLightbulb,
  FaLinux,
  FaMapMarkerAlt,
  FaMedal,
  FaMicrophone,
  FaMoneyBillWave,
  FaMusic,
  FaPalette,
  FaPizzaSlice,
  FaRobot,
  FaRocket,
  FaRunning,
  FaSchool,
  FaStar,
  FaTerminal,
  FaTicketAlt,
  FaTools,
  FaTrophy,
  FaTshirt,
  FaUserGraduate,
  FaUsers,
  FaUsersCog,
  FaUtensils,
  MdCameraAlt,
  MdCampaign,
  MdCardGiftcard,
  MdCelebration,
  MdCode,
  MdComputer,
  MdDirectionsBus,
  MdEmojiEvents,
  MdEvent,
  MdEventAvailable,
  MdFavorite,
  MdGroups,
  MdLightbulb,
  MdLocalBar,
  MdLocalCafe,
  MdLocalPizza,
  MdMenuBook,
  MdMic,
  MdMovie,
  MdMusicNote,
  MdPalette,
  MdRestaurant,
  MdSchool,
  MdScience,
  MdSportsEsports,
  MdSportsSoccer,
  MdStar,
  MdVolunteerActivism,
  MdWork,
  IoBasketball,
  IoBeer,
  IoBook,
  IoBriefcase,
  IoBulb,
  IoBus,
  IoCafe,
  IoCalendar,
  IoCalendarNumber,
  IoCamera,
  IoCart,
  IoCodeSlash,
  IoColorPalette,
  IoFilm,
  IoFlask,
  IoFootball,
  IoGameController,
  IoGift,
  IoGlobe,
  IoHeart,
  IoLibrary,
  IoMegaphone,
  IoMicOutline,
  IoMusicalNotes,
  IoPeople,
  IoPizza,
  IoRestaurant,
  IoRocket,
  IoSchool,
  IoShirt,
  IoStar,
  IoTicket,
  IoTrophy,
  IoWine,
  TbAward,
  TbBallFootball,
  TbBeer,
  TbBook,
  TbBrain,
  TbBriefcase,
  TbBulb,
  TbBus,
  TbCake,
  TbCalendarEvent,
  TbCalendarTime,
  TbCamera,
  TbChess,
  TbCode,
  TbCoffee,
  TbConfetti,
  TbDeviceGamepad,
  TbDeviceLaptop,
  TbFlask,
  TbGift,
  TbHeart,
  TbMedal,
  TbMicrophone,
  TbMovie,
  TbMusic,
  TbPalette,
  TbPizza,
  TbPresentation,
  TbRobot,
  TbRocket,
  TbSchool,
  TbShirt,
  TbSpeakerphone,
  TbStar,
  TbTerminal2,
  TbTicket,
  TbToolsKitchen2,
  TbTrophy,
  TbUsers,
  TbWorld,
  GiBeerStein,
  GiBookshelf,
  GiBrain,
  GiCakeSlice,
  GiCampfire,
  GiChessKnight,
  GiCoffeeCup,
  GiFilmProjector,
  GiFullPizza,
  GiGraduateCap,
  GiGuitar,
  GiHeartPlus,
  GiLaptop,
  GiMicrophone,
  GiPaintBrush,
  GiPartyPopper,
  GiPodium,
  GiPresent,
  GiProcessor,
  GiRobotGolem,
  GiRocketFlight,
  GiRunningShoe,
  GiSoccerBall,
  GiTicket,
  GiTrophy,
  GiVideoCamera,
  HiAcademicCap,
  HiBeaker,
  HiBookOpen,
  HiCake,
  HiCalendarDays,
  HiCamera,
  HiCodeBracket,
  HiComputerDesktop,
  HiFilm,
  HiGift,
  HiGlobeAlt,
  HiHeart,
  HiLightBulb,
  HiMegaphone,
  HiMicrophone,
  HiMusicalNote,
  HiPaintBrush,
  HiRocketLaunch,
  HiSparkles,
  HiStar,
  HiTicket,
  HiTrophy,
  HiUserGroup,
  BsBalloon,
  BsBank,
  BsBook,
  BsBriefcase,
  BsCalendar2Check,
  BsCalendarEvent,
  BsCamera,
  BsCart,
  BsCodeSlash,
  BsController,
  BsCupHot,
  BsEggFried,
  BsFilm,
  BsGift,
  BsGlobe,
  BsHeart,
  BsLaptop,
  BsLightbulb,
  BsMegaphone,
  BsMicFill,
  BsMortarboard,
  BsMusicNoteBeamed,
  BsPalette,
  BsPeople,
  BsRobot,
  BsRocketTakeoff,
  BsStar,
  BsTerminal,
  BsTicketPerforated,
  BsTrophy,
};

export const ICON_NAMES = Object.keys(ICON_REGISTRY);

export const DEFAULT_EVENT_ICON_NAME = "FaCalendar";

export const DEFAULT_EVENT_ICON: IconType = FaCalendar;

/**
 * Every icon name is prefixed by its pack, so the first two characters identify
 * which pack an icon saved before the curated catalogue came from.
 */
const LEGACY_PACK_LOADERS: Record<string, () => Promise<Record<string, unknown>>> = {
  Fa: () => import("react-icons/fa"),
  Md: () => import("react-icons/md"),
  Io: () => import("react-icons/io5"),
  Tb: () => import("react-icons/tb"),
  Gi: () => import("react-icons/gi"),
  Hi: () => import("react-icons/hi2"),
  Bs: () => import("react-icons/bs"),
};

/**
 * Resolves an icon name that is not in the curated catalogue by loading its pack
 * on demand. Keeps events saved with any of the ~21k previously offered icons
 * rendering correctly without putting those packs in the initial bundle.
 */
export async function loadLegacyEventIcon(iconName: string): Promise<IconType | null> {
  const loadPack = LEGACY_PACK_LOADERS[iconName.slice(0, 2)];
  if (!loadPack) return null;

  try {
    const pack = await loadPack();
    const icon = pack[iconName];
    return typeof icon === "function" ? (icon as IconType) : null;
  } catch (error) {
    console.error(`Failed to load icon pack for "${iconName}":`, error);
    return null;
  }
}
